#!/usr/bin/env bash
# Installs this draft into CapCut and opens it. Generated by tools/capcut-build.py.
#
# The draft ships with @@MEDIA_ROOT@@ where the media paths go, so it is not tied to any
# one machine. This fills that in with wherever the repo actually is, worked out from
# where this script sits, then installs the result.
set -u
cd "$(dirname "$0")" || exit 1

DRAFT="15-why-people-say-yes-far-more-often-than-you-think"
PROJECT="projects/15-why-people-say-yes-far-more-often-than-you-think"
DEST="$HOME/Movies/CapCut/User Data/Projects/com.lveditor.draft"

# Finder can start a .command with stdin detached, and a plain read then returns nothing
# straight away, which looks exactly like the user declining. Ask the terminal itself.
ask() {
  reply=""
  if [ -t 0 ] || [ -p /dev/stdin ] || [ -f /dev/stdin ]; then
    printf '%s ' "$1"
    IFS= read -r reply || reply=""
  elif { exec 3<>/dev/tty; } 2>/dev/null; then
    printf '%s ' "$1" >&3
    IFS= read -r reply <&3 || reply=""
    exec 3>&-
  else
    echo "$1" >&2
    echo "There is no terminal here to read the answer from." >&2
    echo "Open Terminal and run this script from there." >&2
    exit 1
  fi
}

# .../<repo>/projects/<project>/edit/capcut/ is four levels down from the repo.
REPO="$(cd ../../../.. 2>/dev/null && pwd)" || REPO=""

if [ ! -d "$DRAFT" ]; then
  echo "Draft folder $DRAFT is missing. Rebuild it with /edit." >&2; exit 1
fi
if [ -z "$REPO" ] || [ ! -d "$REPO/$PROJECT/scenes" ]; then
  echo "Cannot find the project's media from here." >&2
  echo "Expected $REPO/$PROJECT/scenes" >&2
  echo "Keep this script inside the repo, and copy the whole repo to this machine." >&2
  exit 1
fi
if [ ! -d "$DEST" ]; then
  echo "CapCut's draft folder is not here:" >&2
  echo "  $DEST" >&2
  echo "Open CapCut once so it creates it, then run this again." >&2
  exit 1
fi

# CapCut reads its draft list at startup and rewrites drafts on quit, so copying under a
# running CapCut either goes unnoticed or gets overwritten.
if pgrep -x CapCut >/dev/null 2>&1; then
  ask "CapCut is running. Quit it, then press Return to continue."
  if pgrep -x CapCut >/dev/null 2>&1; then
    echo "CapCut is still running. Nothing was copied." >&2; exit 1
  fi
fi

if [ -e "$DEST/$DRAFT" ]; then
  echo "A draft named $DRAFT already exists in CapCut."
  echo "Replacing it discards any editing done to it there."
  ask "Replace it? [y/N]"
  case "$reply" in
    y|Y|yes|YES|Yes) ;;
    *) echo "Nothing was copied. The draft already in CapCut was left alone."; exit 1 ;;
  esac
  rm -rf "$DEST/$DRAFT"
fi

cp -R "$DRAFT" "$DEST/$DRAFT" || exit 1

# Fill in the real paths, in the copy only, so the one in the repo stays portable.
# perl rather than sed: it is on every mac, and the replacement comes from the
# environment so a path full of slashes needs no escaping.
find "$DEST/$DRAFT" -name '*.json' -print0 | while IFS= read -r -d '' f; do
  REPO="$REPO" DEST="$DEST" perl -pi -e     's{[@][@]MEDIA_ROOT[@][@]}{$ENV{REPO}}g; s{[@][@]DRAFT_ROOT[@][@]}{$ENV{DEST}}g; s{[@][@]SEP[@][@]}{/}g' "$f" || exit 1
done

if grep -qr '@@' "$DEST/$DRAFT" 2>/dev/null; then
  echo "Paths were not filled in; CapCut would show every clip offline." >&2
  rm -rf "$DEST/$DRAFT"
  echo "Nothing was installed." >&2; exit 1
fi

# Every file the draft points at, not just the folder holding them. A repo that is
# present but out of date has the folders and not the media, and CapCut shows that as
# every clip in red with no explanation.
missing=$(perl -nE 'while (/"(?:file_)?[Pp]ath":[ ]*"([^"]+)"/g) { say $1 unless -e $1 }' \
  "$DEST/$DRAFT/draft_info.json" "$DEST/$DRAFT/draft_meta_info.json" | sort -u)
if [ -n "$missing" ]; then
  echo "The draft points at files that are not on this machine:" >&2
  echo "$missing" | head -5 | sed 's/^/  /' >&2
  echo "  ... $(echo "$missing" | wc -l | tr -d ' ') in total" >&2
  echo "The repo is here but its media is not. Pull or sync it, then run this again." >&2
  rm -rf "$DEST/$DRAFT"
  echo "Nothing was installed." >&2; exit 1
fi

echo "Installed $DRAFT into CapCut, reading media from $REPO"
open -a CapCut 2>/dev/null || echo "Copied. Open CapCut yourself, it is in the project list."
