@echo off
REM Installs this draft into CapCut and opens it. Generated by tools/capcut-build.py.
REM
REM The draft ships with @@MEDIA_ROOT@@ where the media paths go, so it is not tied to any
REM one machine. This fills that in with wherever the repo actually is, worked out from
REM where this script sits, then installs the result.
setlocal
REM pushd, not cd: cmd refuses a UNC path as a working directory, pushd maps a drive for it.
pushd "%~dp0" || goto nopushd

set "DRAFT=14-the-psychology-of-being-ugly"
set "PROJECT=projects\14-the-psychology-of-being-ugly"
set "DEST=%LOCALAPPDATA%\CapCut\User Data\Projects\com.lveditor.draft"

REM ...\<repo>\projects\<project>\edit\capcut\ is four levels down from the repo.
for %%I in ("%~dp0..\..\..\..") do set "REPO=%%~fI"

if not exist "%DRAFT%\" goto nodraft
if not exist "%REPO%\%PROJECT%\scenes\" goto nomedia
if not exist "%DEST%\" goto nodest

REM CapCut reads its draft list at startup and rewrites drafts on quit, so copying under a
REM running CapCut either goes unnoticed or gets overwritten.
tasklist /fi "imagename eq CapCut.exe" 2>nul | find /i "CapCut.exe" >nul
if errorlevel 1 goto notrunning
echo CapCut is running. Quit it, then press any key to continue.
pause >nul
tasklist /fi "imagename eq CapCut.exe" 2>nul | find /i "CapCut.exe" >nul
if not errorlevel 1 goto stillrunning
:notrunning

if not exist "%DEST%\%DRAFT%\" goto copyit
echo A draft named %DRAFT% already exists in CapCut.
echo Replacing it discards any editing done to it there.
set "reply="
set /p reply="Replace it? [y/N] "
if /i "%reply%"=="y" goto doreplace
if /i "%reply%"=="yes" goto doreplace
goto cancelled
:doreplace
rmdir /s /q "%DEST%\%DRAFT%"

:copyit
xcopy "%DRAFT%" "%DEST%\%DRAFT%\" /E /I /Q /Y >nul
if errorlevel 1 goto copyfailed
set "TARGET=%DEST%\%DRAFT%"

REM Fill in the real paths, in the copy only, so the one in the repo stays portable.
REM Backslashes are doubled because these land inside JSON strings.
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$r=$env:REPO -replace '\','\\'; $d=$env:DEST -replace '\','\\';" ^
  "Get-ChildItem -Path $env:TARGET -Recurse -Filter *.json | ForEach-Object {" ^
  "  $t=[IO.File]::ReadAllText($_.FullName);" ^
  "  $t=$t.Replace('@@MEDIA_ROOT@@',$r).Replace('@@DRAFT_ROOT@@',$d).Replace('@@SEP@@','\\');" ^
  "  [IO.File]::WriteAllText($_.FullName,$t) }"
if errorlevel 1 goto rewritefailed

findstr /s /m /c:"@@" "%DEST%\%DRAFT%\*.json" >nul 2>&1
if not errorlevel 1 goto rewritefailed

REM Every file the draft points at, not just the folder holding them.
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$t=[IO.File]::ReadAllText("$env:TARGET\draft_info.json");" ^
  "$m=[regex]::Matches($t,'"(?:file_)?[Pp]ath":"([^"]+)"') ^| " ^
  "  ForEach-Object { $_.Groups[1].Value -replace '\\','\' } ^| " ^
  "  Where-Object { $_ -and -not (Test-Path -LiteralPath $_) } ^| Select-Object -Unique;" ^
  "if ($m) { $m ^| Select-Object -First 5 ^| ForEach-Object { Write-Host "  $_" };" ^
  "  Write-Host "  ... $($m.Count) in total"; exit 1 }"
if errorlevel 1 goto mediamissing

echo Installed %DRAFT% into CapCut, reading media from:
REM Quoted: an unquoted path containing & would run as a command here.
echo   "%REPO%"

for /f "delims=" %%A in ('dir /b /o-n "%LOCALAPPDATA%\CapCut\Apps" 2^>nul') do (
  if exist "%LOCALAPPDATA%\CapCut\Apps\%%A\CapCut.exe" (
    start "" "%LOCALAPPDATA%\CapCut\Apps\%%A\CapCut.exe"
    goto done
  )
)
echo Copied. Open CapCut yourself, it is in the project list.
goto done

:nodraft
echo Draft folder %DRAFT% is missing. Rebuild it with /edit.
goto fail
:nomedia
echo Cannot find the project's media from here.
echo Expected "%REPO%\%PROJECT%\scenes"
echo Keep this script inside the repo, and copy the whole repo to this machine.
goto fail
:nodest
echo CapCut's draft folder is not here:
echo   "%DEST%"
echo Open CapCut once so it creates it, then run this again.
goto fail
:stillrunning
echo CapCut is still running. Nothing was copied.
goto fail
:cancelled
echo Nothing was copied. The draft already in CapCut was left alone.
goto fail
:copyfailed
echo Copy failed.
goto fail
:mediamissing
echo The draft points at files that are not on this machine.
echo The repo is here but its media is not. Pull or sync it, then run this again.
rmdir /s /q "%DEST%\%DRAFT%" 2>nul
echo Nothing was installed.
goto fail
:rewritefailed
echo Paths were not filled in; CapCut would show every clip offline.
rmdir /s /q "%DEST%\%DRAFT%" 2>nul
echo Nothing was installed.
goto fail

:nopushd
echo Cannot enter this folder. If it is on a network share, map it to a drive letter first.
pause
exit /b 1

:fail
popd
pause
exit /b 1
:done
popd
pause
