#!/usr/bin/env bash
# Opens this project in Kdenlive. Generated by tools/kdenlive-build.py.
cd "$(dirname "$0")" || exit 1
project="14-the-psychology-of-being-ugly.kdenlive"
if [ ! -f "$project" ]; then
  echo "$project is missing. Rebuild it with /edit." >&2; exit 1
fi
if ! command -v kdenlive >/dev/null 2>&1; then
  echo "Kdenlive is not installed, or not on PATH." >&2; exit 1
fi
# An XML formatter moves a <property> value onto its own line, and MLT then
# reads the scene path with the indentation attached, so every clip goes
# missing. Catch that here rather than in a dialog listing 290 missing clips.
if grep -q 'name="resource">$' "$project"; then
  echo "$project has been reformatted and its clip paths are broken." >&2
  echo "Something saved it through an XML formatter, VS Code format-on-save" >&2
  echo "being the usual one. Rebuild it:" >&2
  echo "  python3 tools/kdenlive-build.py <project> --logo brand/logo.png --force" >&2
  exit 1
fi
# Detach, so closing the terminal does not close the editor.
(setsid kdenlive "$project" >/dev/null 2>&1 &) 2>/dev/null \
  || (nohup kdenlive "$project" >/dev/null 2>&1 &)
