#!/usr/bin/env python3
"""Build a CapCut draft that cuts the scene images on the transcript's own timestamps.

The companion to tools/kdenlive-build.py. Both read the same cut plan from tools/cuts.py,
so a project assembled in CapCut lands on exactly the frames it would in Kdenlive.

CapCut has no timeline import format, so this writes its draft folder directly. Every
object is cloned from a template extracted from a real CapCut draft rather than written
from scratch, because the format is undocumented and the fields that matter are not the
ones that look important.

    python3 tools/capcut-build.py projects/13-the-psychology-of-being-poor \\
        --media-root /Users/htnt/Me/Things/Build-a-Channel

Copy the resulting folder into CapCut's draft directory and it appears in the project
list. The paths inside point at the media on the machine that will open it, which is why
--media-root is required: this repo lives somewhere else on that machine.
"""

import argparse
import copy
import json
import sys
import time
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import cuts  # noqa: E402

# The draft ships with these in place of absolute paths, and the installer substitutes
# the real ones on the machine it runs on. Nothing here has to know where the repo lives
# there, which is what makes one draft work on every device.
MEDIA_TOKEN = "@@MEDIA_ROOT@@"
DRAFT_TOKEN = "@@DRAFT_ROOT@@"
# The separator is a token too, so one draft serves both machines and the installers
# need nothing cleverer than three plain string replacements.
SEP_TOKEN = "@@SEP@@"

TEMPLATE = (
    Path(__file__).resolve().parent.parent
    / ".agents/skills/edit/templates/capcut-9.1-mac.json"
)

# Where CapCut keeps its drafts, written so the installer resolves it on the machine it runs on rather
# than trusting a username baked in here.
DRAFT_ROOT_VARS = {
    "mac": "$HOME/Movies/CapCut/User Data/Projects/com.lveditor.draft",
    "windows": "%LOCALAPPDATA%/CapCut/User Data/Projects/com.lveditor.draft",
}


# CapCut counts in microseconds, and gives every still the same nominal three hours.
STILL_DURATION = 10_800_000_000


MAC_INSTALLER = """#!/usr/bin/env bash
# Installs this draft into CapCut and opens it. Generated by tools/capcut-build.py.
#
# The draft ships with @@MEDIA_ROOT@@ where the media paths go, so it is not tied to any
# one machine. This fills that in with wherever the repo actually is, worked out from
# where this script sits, then installs the result.
set -u
cd "$(dirname "$0")" || exit 1

DRAFT=<<DRAFT>>
PROJECT=<<PROJECT>>
DEST=<<DEST>>

# Finder can start a .command with stdin detached, and a plain read then returns nothing
# straight away, which looks exactly like the user declining. Ask the terminal itself.
ask() {
  reply=""
  if [ -t 0 ] || [ -p /dev/stdin ] || [ -f /dev/stdin ]; then
    printf '%s ' "$1"
    IFS= read -r reply || reply=""
  elif { exec 3<>/dev/tty; } 2>/dev/null; then
    printf '%s ' "$1" >&3
    IFS= read -r reply <&3 || reply=""
    exec 3>&-
  else
    echo "$1" >&2
    echo "There is no terminal here to read the answer from." >&2
    echo "Open Terminal and run this script from there." >&2
    exit 1
  fi
}

# .../<repo>/projects/<project>/edit/capcut/ is four levels down from the repo.
REPO="$(cd ../../../.. 2>/dev/null && pwd)" || REPO=""

if [ ! -d "$DRAFT" ]; then
  echo "Draft folder $DRAFT is missing. Rebuild it with /edit." >&2; exit 1
fi
if [ -z "$REPO" ] || [ ! -d "$REPO/$PROJECT/scenes" ]; then
  echo "Cannot find the project's media from here." >&2
  echo "Expected $REPO/$PROJECT/scenes" >&2
  echo "Keep this script inside the repo, and copy the whole repo to this machine." >&2
  exit 1
fi
if [ ! -d "$DEST" ]; then
  echo "CapCut's draft folder is not here:" >&2
  echo "  $DEST" >&2
  echo "Open CapCut once so it creates it, then run this again." >&2
  exit 1
fi

# CapCut reads its draft list at startup and rewrites drafts on quit, so copying under a
# running CapCut either goes unnoticed or gets overwritten.
if pgrep -x CapCut >/dev/null 2>&1; then
  ask "CapCut is running. Quit it, then press Return to continue."
  if pgrep -x CapCut >/dev/null 2>&1; then
    echo "CapCut is still running. Nothing was copied." >&2; exit 1
  fi
fi

if [ -e "$DEST/$DRAFT" ]; then
  echo "A draft named $DRAFT already exists in CapCut."
  echo "Replacing it discards any editing done to it there."
  ask "Replace it? [y/N]"
  case "$reply" in
    y|Y|yes|YES|Yes) ;;
    *) echo "Nothing was copied. The draft already in CapCut was left alone."; exit 1 ;;
  esac
  rm -rf "$DEST/$DRAFT"
fi

cp -R "$DRAFT" "$DEST/$DRAFT" || exit 1

# Fill in the real paths, in the copy only, so the one in the repo stays portable.
# perl rather than sed: it is on every mac, and the replacement comes from the
# environment so a path full of slashes needs no escaping.
find "$DEST/$DRAFT" -name '*.json' -print0 | while IFS= read -r -d '' f; do
  REPO="$REPO" DEST="$DEST" perl -pi -e \
    's{[@][@]MEDIA_ROOT[@][@]}{$ENV{REPO}}g; s{[@][@]DRAFT_ROOT[@][@]}{$ENV{DEST}}g; s{[@][@]SEP[@][@]}{/}g' "$f" || exit 1
done

if grep -qr '@@' "$DEST/$DRAFT" 2>/dev/null; then
  echo "Paths were not filled in; CapCut would show every clip offline." >&2
  rm -rf "$DEST/$DRAFT"
  echo "Nothing was installed." >&2; exit 1
fi

# Every file the draft points at, not just the folder holding them. A repo that is
# present but out of date has the folders and not the media, and CapCut shows that as
# every clip in red with no explanation.
missing=$(perl -nE 'while (/"(?:file_)?[Pp]ath":[ ]*"([^"]+)"/g) { say $1 unless -e $1 }' \\
  "$DEST/$DRAFT/draft_info.json" "$DEST/$DRAFT/draft_meta_info.json" | sort -u)
if [ -n "$missing" ]; then
  echo "The draft points at files that are not on this machine:" >&2
  echo "$missing" | head -5 | sed 's/^/  /' >&2
  echo "  ... $(echo "$missing" | wc -l | tr -d ' ') in total" >&2
  echo "The repo is here but its media is not. Pull or sync it, then run this again." >&2
  rm -rf "$DEST/$DRAFT"
  echo "Nothing was installed." >&2; exit 1
fi

echo "Installed $DRAFT into CapCut, reading media from $REPO"
open -a CapCut 2>/dev/null || echo "Copied. Open CapCut yourself, it is in the project list."
"""

WINDOWS_INSTALLER = """@echo off
REM Installs this draft into CapCut and opens it. Generated by tools/capcut-build.py.
REM
REM The draft ships with @@MEDIA_ROOT@@ where the media paths go, so it is not tied to any
REM one machine. This fills that in with wherever the repo actually is, worked out from
REM where this script sits, then installs the result.
setlocal
REM pushd, not cd: cmd refuses a UNC path as a working directory, pushd maps a drive for it.
pushd "%~dp0" || goto nopushd

set "DRAFT=<<DRAFT>>"
set "PROJECT=<<PROJECT>>"
set "DEST=<<DEST>>"

REM ...\\<repo>\\projects\\<project>\\edit\\capcut\\ is four levels down from the repo.
for %%I in ("%~dp0..\\..\\..\\..") do set "REPO=%%~fI"

if not exist "%DRAFT%\\" goto nodraft
if not exist "%REPO%\\%PROJECT%\\scenes\\" goto nomedia
if not exist "%DEST%\\" goto nodest

REM CapCut reads its draft list at startup and rewrites drafts on quit, so copying under a
REM running CapCut either goes unnoticed or gets overwritten.
tasklist /fi "imagename eq CapCut.exe" 2>nul | find /i "CapCut.exe" >nul
if errorlevel 1 goto notrunning
echo CapCut is running. Quit it, then press any key to continue.
pause >nul
tasklist /fi "imagename eq CapCut.exe" 2>nul | find /i "CapCut.exe" >nul
if not errorlevel 1 goto stillrunning
:notrunning

if not exist "%DEST%\\%DRAFT%\\" goto copyit
echo A draft named %DRAFT% already exists in CapCut.
echo Replacing it discards any editing done to it there.
set "reply="
set /p reply="Replace it? [y/N] "
if /i "%reply%"=="y" goto doreplace
if /i "%reply%"=="yes" goto doreplace
goto cancelled
:doreplace
rmdir /s /q "%DEST%\\%DRAFT%"

:copyit
xcopy "%DRAFT%" "%DEST%\\%DRAFT%\\" /E /I /Q /Y >nul
if errorlevel 1 goto copyfailed
set "TARGET=%DEST%\\%DRAFT%"

REM Fill in the real paths, in the copy only, so the one in the repo stays portable.
REM Backslashes are doubled because these land inside JSON strings.
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$r=$env:REPO -replace '\\','\\\\'; $d=$env:DEST -replace '\\','\\\\';" ^
  "Get-ChildItem -Path $env:TARGET -Recurse -Filter *.json | ForEach-Object {" ^
  "  $t=[IO.File]::ReadAllText($_.FullName);" ^
  "  $t=$t.Replace('@@MEDIA_ROOT@@',$r).Replace('@@DRAFT_ROOT@@',$d).Replace('@@SEP@@','\\\\');" ^
  "  [IO.File]::WriteAllText($_.FullName,$t) }"
if errorlevel 1 goto rewritefailed

findstr /s /m /c:"@@" "%DEST%\\%DRAFT%\\*.json" >nul 2>&1
if not errorlevel 1 goto rewritefailed

REM Every file the draft points at, not just the folder holding them.
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$t=[IO.File]::ReadAllText(\"$env:TARGET\\draft_info.json\");" ^
  "$m=[regex]::Matches($t,'\"(?:file_)?[Pp]ath\":\"([^\"]+)\"') ^| " ^
  "  ForEach-Object { $_.Groups[1].Value -replace '\\\\','\\' } ^| " ^
  "  Where-Object { $_ -and -not (Test-Path -LiteralPath $_) } ^| Select-Object -Unique;" ^
  "if ($m) { $m ^| Select-Object -First 5 ^| ForEach-Object { Write-Host \"  $_\" };" ^
  "  Write-Host \"  ... $($m.Count) in total\"; exit 1 }"
if errorlevel 1 goto mediamissing

echo Installed %DRAFT% into CapCut, reading media from:
REM Quoted: an unquoted path containing & would run as a command here.
echo   "%REPO%"

for /f "delims=" %%A in ('dir /b /o-n "%LOCALAPPDATA%\\CapCut\\Apps" 2^>nul') do (
  if exist "%LOCALAPPDATA%\\CapCut\\Apps\\%%A\\CapCut.exe" (
    start "" "%LOCALAPPDATA%\\CapCut\\Apps\\%%A\\CapCut.exe"
    goto done
  )
)
echo Copied. Open CapCut yourself, it is in the project list.
goto done

:nodraft
echo Draft folder %DRAFT% is missing. Rebuild it with /edit.
goto fail
:nomedia
echo Cannot find the project's media from here.
echo Expected "%REPO%\\%PROJECT%\\scenes"
echo Keep this script inside the repo, and copy the whole repo to this machine.
goto fail
:nodest
echo CapCut's draft folder is not here:
echo   "%DEST%"
echo Open CapCut once so it creates it, then run this again.
goto fail
:stillrunning
echo CapCut is still running. Nothing was copied.
goto fail
:cancelled
echo Nothing was copied. The draft already in CapCut was left alone.
goto fail
:copyfailed
echo Copy failed.
goto fail
:mediamissing
echo The draft points at files that are not on this machine.
echo The repo is here but its media is not. Pull or sync it, then run this again.
rmdir /s /q "%DEST%\\%DRAFT%" 2>nul
echo Nothing was installed.
goto fail
:rewritefailed
echo Paths were not filled in; CapCut would show every clip offline.
rmdir /s /q "%DEST%\\%DRAFT%" 2>nul
echo Nothing was installed.
goto fail

:nopushd
echo Cannot enter this folder. If it is on a network share, map it to a drive letter first.
pause
exit /b 1

:fail
popd
pause
exit /b 1
:done
popd
pause
"""


def fill(template, draft, project, dest):
    """Substitute into an installer template. Not str.format: these are shell and batch,
    and both are full of braces that format would try to read as fields."""
    return (template.replace("<<DRAFT>>", draft)
                    .replace("<<PROJECT>>", project)
                    .replace("<<DEST>>", dest))


def us(frames, fps):
    """Frames to microseconds. The plan is in frames; CapCut is not."""
    return int(round(frames * 1_000_000 / fps))


def uid():
    return str(uuid.uuid4()).upper()


def join(root, *parts, sep="/"):
    """Path on the machine that will open the draft, not on this one.

    The separator is passed in, never sniffed off the root: the root is a placeholder
    the installer fills in later, so there is no drive letter to read it from.
    """
    return sep.join([root.rstrip("/\\")] + [str(p).replace("/", sep) for p in parts])


def build(args):
    project = Path(args.project).resolve()
    tmpl = json.loads(TEMPLATE.read_text(encoding="utf-8"))

    media_root = MEDIA_TOKEN

    fps = args.fps
    plan = cuts.plan(project, fps, args.allow_gaps, args.audio, args.duration)
    repo = Path(__file__).resolve().parent.parent

    def remote(path):
        """A path the installer will complete, relative to wherever the repo is there."""
        return join(media_root, Path(path).resolve().relative_to(repo), sep=SEP_TOKEN)

    # Canvas follows the scene images, the way CapCut derives it from the first clip.
    size = cuts.image_size(plan.cuts[0][2]) or (1920, 1080)
    width = args.width or 1920
    height = args.height or int(round(width * size[1] / size[0])) // 2 * 2

    now = int(time.time() * 1_000_000)
    now_s = int(time.time())

    materials = {k: [] for k in (
        "videos", "audios", "canvases", "speeds", "placeholder_infos",
        "sound_channel_mappings", "material_colors", "loudnesses",
        "vocal_separations", "beats",
    )}

    def aux(bucket):
        """One private copy of a shared auxiliary material, with a fresh id."""
        obj = copy.deepcopy(tmpl["aux"][bucket])
        obj["id"] = uid()
        materials[bucket].append(obj)
        return obj["id"]

    # draft_meta_info's draft_materials is the Media bin. Leaving it empty leaves the bin
    # empty, which is how a draft that otherwise looks right arrives with nothing to
    # re-drag and every clip reported as not accessible.
    bin_entries = []

    def bin_entry(path, metetype, duration, width, height):
        entry_id = str(uuid.uuid4())
        bin_entries.append({
            "ai_group_type": "", "create_time": now_s, "duration": duration,
            "enter_from": 0, "extra_info": Path(path).name, "file_Path": remote(path),
            "height": height, "id": entry_id, "import_time": now_s,
            "import_time_ms": now, "item_source": 1, "material_color_tag": "",
            "md5": "", "metetype": metetype,
            "roughcut_time_range": ({"duration": duration, "start": 0}
                                    if metetype == "music" else
                                    {"duration": -1, "start": -1}),
            "sub_time_range": {"duration": -1, "start": -1},
            "type": 0, "width": width,
        })
        return entry_id

    def photo(path, name=None):
        obj = copy.deepcopy(tmpl["photo_material"])
        w, h = cuts.image_size(path) or (0, 0)
        obj.update(id=uid(), path=remote(path), width=w, height=h,
                   material_name=name or Path(path).name, duration=STILL_DURATION)
        materials["videos"].append(obj)
        bin_entry(path, "photo", 5_000_000, w, h)
        return obj["id"]

    def video_segment(material_id, start_us, end_us, clip=None, index=0):
        seg = copy.deepcopy(tmpl["video_segment"])
        seg["id"] = uid()
        seg["material_id"] = material_id
        seg["extra_material_refs"] = [aux(b) for b in tmpl["video_ref_order"]]
        span = {"start": start_us, "duration": end_us - start_us}
        seg["target_timerange"] = dict(span)
        seg["source_timerange"] = {"start": 0, "duration": span["duration"]}
        seg["render_index"] = index
        seg["track_render_index"] = index
        if clip:
            seg["clip"] = clip
        return seg

    # V1: one segment per scene, each held until the next cue. Every boundary is taken
    # from the microsecond position of the next cue, never from a separately rounded
    # duration: round(a) + round(b) is not round(a + b), and at 30fps a frame is
    # 33333.33us, so rounding each duration on its own leaves a gap at most boundaries.
    bounds = [us(start, fps) for start, _, _ in plan.cuts] + [us(plan.total_frames, fps)]
    scene_segments = [
        video_segment(photo(path), bounds[i], bounds[i + 1], index=i)
        for i, (_, _, path) in enumerate(plan.cuts)
    ]

    tracks = []
    v1 = copy.deepcopy(tmpl["video_track"])
    v1.update(id=uid(), segments=scene_segments)
    tracks.append(v1)

    # V2: the logo, held over the whole video, placed by normalised offset from centre.
    if args.logo:
        logo = Path(args.logo).resolve()
        if not logo.exists():
            raise SystemExit(f"no logo at {logo}")
        lw, lh = cuts.image_size(logo) or (1, 1)
        x, y, w, h = cuts.logo_box(width, height, args.logo_size,
                                   args.logo_right, args.logo_bottom)
        # CapCut fits the image to the canvas first, then applies scale, so a scale of 1
        # is already the fitted size and not the source pixels. Confirmed against a real
        # draft: scale 0.07092 on a 1254px logo in a 1920x1072 canvas renders 76px.
        fit = min(width / lw, height / lh)
        clip = copy.deepcopy(tmpl["video_segment"]["clip"])
        clip["scale"] = {"x": w / (lw * fit), "y": w / (lw * fit)}
        # transform is the centre, normalised to -1..1 from the middle of the frame.
        clip["transform"] = {
            "x": ((x + w / 2) - width / 2) / (width / 2),
            "y": -(((y + h / 2) - height / 2) / (height / 2)),
        }
        v2 = copy.deepcopy(tmpl["video_track"])
        v2.update(id=uid(), flag=2, segments=[
            video_segment(photo(logo), 0, bounds[-1], clip=clip)
        ])
        tracks.append(v2)

    # A1: the narration, one segment running the whole timeline.
    audio_mat = copy.deepcopy(tmpl["audio_material"])
    audio_seconds = cuts.audio_seconds(plan.audio)
    audio_us = int(round(audio_seconds * 1_000_000))
    audio_mat.update(id=uid(), path=remote(plan.audio), name=plan.audio.name,
                     duration=audio_us, music_id=str(uuid.uuid4()),
                     local_material_id=bin_entry(plan.audio, "music", audio_us, 0, 0))
    materials["audios"].append(audio_mat)

    a_seg = copy.deepcopy(tmpl["audio_segment"])
    a_seg["id"] = uid()
    a_seg["material_id"] = audio_mat["id"]
    a_seg["extra_material_refs"] = [aux(b) for b in tmpl["audio_ref_order"]]
    span = {"start": 0, "duration": bounds[-1]}
    a_seg["target_timerange"] = dict(span)
    a_seg["source_timerange"] = dict(span)
    a1 = copy.deepcopy(tmpl["audio_track"])
    a1.update(id=uid(), segments=[a_seg])
    tracks.append(a1)

    timeline_id, draft_id, project_id = uid(), uid(), uid()

    doc = copy.deepcopy(tmpl["document"])
    doc.update(
        id=timeline_id,
        duration=bounds[-1],
        fps=float(fps),
        canvas_config={"ratio": "original", "width": width, "height": height,
                       "background": None},
        materials={**doc.get("materials", {}), **materials},
        tracks=tracks,
        create_time=now,
        update_time=now,
        name="",
        path="",
    )
    for empty in ("keyframes", "keyframe_graph_list", "relationships", "time_marks"):
        if empty in doc and isinstance(doc[empty], list):
            doc[empty] = []

    name = args.name or project.name
    # One subfolder per target machine: the media paths inside a draft are absolute
    # and OS specific, so a mac draft and a windows draft are different files.
    out = Path(args.out).resolve() if args.out else project / "edit" / "capcut" / name
    if out.exists() and not args.force and not args.dry_run:
        raise SystemExit(
            f"{out} already exists. A draft opened in CapCut holds hand work no rebuild\n"
            f"can recover, so pass --force to overwrite or --out to write another."
        )

    if args.dry_run:
        for start, length, path in plan.cuts:
            print(f"{cuts.tc(start, fps)}  {length:5d}f  {length / fps:6.2f}s  {path.name}")
        print(f"\n{len(plan)} scenes, {cuts.tc(plan.total_frames, fps)} total, {fps} fps, "
              f"{width}x{height}")
        for line in plan.report:
            print(f"note: {line}")
        print(f"would write {out}")
        return

    draft_root = args.draft_root or DRAFT_TOKEN
    fold = join(draft_root, name, sep=SEP_TOKEN)
    meta = {
        "draft_cover": "draft_cover.jpg",
        "draft_fold_path": fold,
        "draft_id": draft_id,
        "draft_name": name,
        "draft_root_path": draft_root,
        "draft_removable_storage_device": "",
        "draft_timeline_materials_size_": 0,
        "draft_type": "",
        "tm_draft_create": now,
        "tm_draft_modified": now,
        "tm_draft_removed": 0,
        "tm_duration": doc["duration"],
        "draft_materials": [{"type": 0, "value": bin_entries}]
                           + [{"type": t, "value": []} for t in (1, 2, 3, 6, 7, 8)],
        "draft_materials_copied_info": [],
        "draft_segment_extra_info": [],
        "draft_enterprise_info": {"draft_enterprise_extra": "",
                                  "draft_enterprise_id": "",
                                  "draft_enterprise_name": "",
                                  "enterprise_material": []},
        "draft_is_ai_shorts": False,
        "draft_is_invisible": False,
        "draft_new_version": "",
    }

    out.mkdir(parents=True, exist_ok=True)
    (out / "Timelines" / timeline_id).mkdir(parents=True, exist_ok=True)
    body = json.dumps(doc, ensure_ascii=False)
    # CapCut keeps the timeline in both places and they are byte-identical.
    (out / "draft_info.json").write_text(body, encoding="utf-8")
    (out / "Timelines" / timeline_id / "draft_info.json").write_text(body, encoding="utf-8")
    (out / "draft_meta_info.json").write_text(json.dumps(meta, ensure_ascii=False),
                                              encoding="utf-8")
    (out / "Timelines" / "project.json").write_text(json.dumps({
        "config": {"color_space": -1, "mixed_track_mode_on": False,
                   "render_index_track_mode_on": False, "use_float_render": False},
        "create_time": now, "id": project_id, "main_timeline_id": timeline_id,
        "timelines": [{"create_time": now, "id": timeline_id, "is_marked_delete": False,
                       "name": "Timeline 01", "update_time": now}],
        "update_time": now, "version": 0,
    }, ensure_ascii=False), encoding="utf-8")

    # Both launchers beside the draft, never inside it: anything inside would be copied
    # into CapCut's own folder along with the timeline. The draft itself is the same file
    # on either machine, so there is one of it and two ways to install it.
    rel = str(project.relative_to(repo))
    mac = out.parent / "install-mac.command"
    mac.write_text(
        fill(MAC_INSTALLER, json.dumps(name), json.dumps(rel),
             json.dumps(args.draft_root or DRAFT_ROOT_VARS["mac"])),
        encoding="utf-8")
    mac.chmod(0o755)
    win = out.parent / "install-windows.bat"
    win.write_text(
        fill(WINDOWS_INSTALLER, name, rel.replace("/", "\\"),
             (args.draft_root or DRAFT_ROOT_VARS["windows"]).replace("/", "\\")),
        encoding="utf-8", newline="\r\n")

    print(out)
    print(f"  {mac.name} installs it on a Mac, {win.name} on Windows")
    print(f"  {len(plan)} scenes" + (", logo" if args.logo else "")
          + f", narration, {cuts.tc(plan.total_frames, fps)} at {fps} fps, {width}x{height}")
    print("  paths resolve from wherever the repo sits on that machine")
    for line in plan.report:
        print(f"  note: {line}")


def main():
    p = argparse.ArgumentParser(
        description="Cut a project's scene images onto a CapCut timeline at their "
                    "transcript times.")
    p.add_argument("project", help="projects/<n>-<slug>")
    p.add_argument("--draft-root", help="CapCut draft directory on that machine")
    p.add_argument("--name", help="draft name, and the folder name (default the project)")
    p.add_argument("--out", help="where to write the draft folder locally")
    p.add_argument("--audio", help="narration file (default <project>/audios/full.mp3)")
    p.add_argument("--duration", type=float, help="override the narration length")
    p.add_argument("--fps", type=int, default=30)
    p.add_argument("--width", type=int, help="canvas width (default 1920)")
    p.add_argument("--height", type=int, help="canvas height (default from image aspect)")
    p.add_argument("--logo", help="image to hold on V2 for the whole video")
    p.add_argument("--logo-size", type=float,
                   help="logo width as a fraction of the frame width")
    p.add_argument("--logo-right", type=float,
                   help="gap to the right of the logo, as a fraction of the frame width")
    p.add_argument("--logo-bottom", type=float,
                   help="gap below the logo, as a fraction of the frame height")
    p.add_argument("--allow-gaps", action="store_true",
                   help="build even though some cues have no scene image yet")
    p.add_argument("--force", action="store_true", help="overwrite an existing draft")
    p.add_argument("--dry-run", action="store_true", help="print the cut list, write nothing")
    build(p.parse_args())


if __name__ == "__main__":
    main()
